package com.example.notification.service;
import com.example.notification.dto.NotificationEvent; import com.example.notification.model.ProcessedEvent; import com.example.notification.repository.ProcessedEventRepository; import com.fasterxml.jackson.databind.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.client.RestTemplate; import org.springframework.web.util.UriComponentsBuilder;
import java.time.*;
@Service public class DeadlineReminderJob {
 private final NotificationService notifications;private final ProcessedEventRepository processed;private final RestTemplate http=new RestTemplate();private final ObjectMapper json=new ObjectMapper().findAndRegisterModules();private final String taskUrl;private final int pageSize;
 public DeadlineReminderJob(NotificationService n,ProcessedEventRepository p,@Value("${task-service.url:http://localhost:8082}")String url,@Value("${notification.deadline.page-size:200}")int size){notifications=n;processed=p;taskUrl=url;pageSize=size;}
 @Scheduled(cron="${notification.deadline.cron:0 0 * * * *}") @Transactional public void remind(){for(int page=0;;page++){try{String uri=UriComponentsBuilder.fromHttpUrl(taskUrl+"/api/tasks").queryParam("page",page).queryParam("size",pageSize).toUriString();JsonNode root=json.readTree(http.getForObject(uri,String.class));for(JsonNode t:root.path("data"))process(t);if(page+1>=root.path("page").path("totalPages").asInt(1))break;}catch(Exception e){throw new IllegalStateException("Cannot scan task deadlines",e);}}}
 private void process(JsonNode t){String assignee=t.path("assignee").asText("");String due=t.path("dueDate").asText("");if(assignee.isEmpty()||due.isEmpty()||"COMPLETED".equals(t.path("status").asText()))return;LocalDateTime deadline=LocalDateTime.parse(due),now=LocalDateTime.now();String type=deadline.isBefore(now)?"TASK_OVERDUE":deadline.isBefore(now.plusHours(24))?"TASK_DUE_SOON":null;if(type==null)return;String id="deadline:"+type+":"+t.path("id").asLong()+":"+LocalDate.now();if(processed.existsById(id))return;processed.saveAndFlush(new ProcessedEvent(id));NotificationEvent e=new NotificationEvent();e.setEventId(id);e.setType(type);e.setRecipient(assignee);e.setResourceId(t.path("id").asLong());e.setResourceType("TASK");e.setTitle(type.equals("TASK_OVERDUE")?"Task overdue":"Task due soon");e.setMessage(t.path("title").asText("Task")+" is due at "+deadline);notifications.processEvent(e);}
}
