package com.example.task.controller;
import com.example.common.dto.ApiResponse;import com.example.task.dto.*;import com.example.task.model.*;import com.example.task.service.TaskService;import org.springframework.data.domain.Page;import org.springframework.web.bind.annotation.*;import javax.validation.Valid;import java.util.*;
@RestController @RequestMapping("/api/tasks") public class TaskController {
 private final TaskService service;public TaskController(TaskService s){service=s;}
 @GetMapping public ApiResponse<List<TaskDTO>> list(@RequestHeader(value="X-Workspace-Id",required=false)Long headerWorkspace,@RequestParam(required=false)Long workspaceId,@RequestParam(required=false)Long projectId,@RequestParam(required=false)String assignee,@RequestParam(required=false)Long parentTaskId,@RequestParam(required=false)Status status,@RequestParam(required=false)Priority priority,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)String search,@RequestParam(defaultValue="false")boolean includeArchived,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="position")String sort){Long scope=headerWorkspace==null?workspaceId:headerWorkspace;Page<TaskDTO> p=service.getTasks(scope,projectId,assignee,parentTaskId,status,priority,categoryId,search,includeArchived,page,size,sort);return ApiResponse.okPage("Tasks retrieved",p.getContent(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @GetMapping("/stats") public ApiResponse<TaskStatsDTO> stats(@RequestHeader("X-Workspace-Id")Long w){return ApiResponse.ok("Stats retrieved",service.stats(w));}
 @GetMapping("/{id}") public ApiResponse<TaskDTO> get(@PathVariable Long id,@RequestHeader(value="X-Workspace-Id",required=false)Long w){return ApiResponse.ok("Task retrieved",service.get(id,w));}
 @PostMapping public ApiResponse<TaskDTO> create(@Valid @RequestBody TaskDTO d,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u,@RequestHeader(value="X-Workspace-Role",required=false)String role){d.setWorkspaceId(w);return ApiResponse.ok("Task created",service.create(d,u,role));}
 @PutMapping("/{id}") public ApiResponse<TaskDTO> update(@PathVariable Long id,@Valid @RequestBody TaskDTO d,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u,@RequestHeader(value="X-Workspace-Role",required=false)String role){return ApiResponse.ok("Task updated",service.update(id,d,w,u,role));}
 @PatchMapping("/{id}/status") public ApiResponse<TaskDTO> status(@PathVariable Long id,@RequestBody Map<String,String>b,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u,@RequestHeader(value="X-Workspace-Role",required=false)String role){return ApiResponse.ok("Status updated",service.status(id,Status.valueOf(b.get("status")),Long.valueOf(b.get("version")),w,u,role));}
 @PatchMapping("/bulk") public ApiResponse<List<TaskDTO>> bulk(@RequestBody BulkTaskUpdateRequest r,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u,@RequestHeader(value="X-Workspace-Role",required=false)String role){return ApiResponse.ok("Tasks updated",service.bulk(r,w,u,role));}
 @DeleteMapping("/{id}") public ApiResponse<TaskDTO> archive(@PathVariable Long id,@RequestParam Long version,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u){return ApiResponse.ok("Task archived",service.archive(id,version,w,u));}
 @PutMapping("/{id}/restore") public ApiResponse<TaskDTO> restore(@PathVariable Long id,@RequestParam Long version,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u){return ApiResponse.ok("Task restored",service.restore(id,version,w,u));}
 @PostMapping("/{id}/watchers/{username}") public ApiResponse<TaskDTO> addWatcher(@PathVariable Long id,@PathVariable String username,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u,@RequestHeader(value="X-Workspace-Role",required=false)String role){return ApiResponse.ok("Watcher added",service.watcher(id,username,true,w,u,role));}
 @DeleteMapping("/{id}/watchers/{username}") public ApiResponse<TaskDTO> removeWatcher(@PathVariable Long id,@PathVariable String username,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u,@RequestHeader(value="X-Workspace-Role",required=false)String role){return ApiResponse.ok("Watcher removed",service.watcher(id,username,false,w,u,role));}
 @PostMapping("/{id}/dependencies/{other}") public ApiResponse<TaskDTO> dependency(@PathVariable Long id,@PathVariable Long other,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u){return ApiResponse.ok("Dependency added",service.addDependency(id,other,w,u));}
 @DeleteMapping("/{id}/dependencies/{other}") public ApiResponse<Void> removeDependency(@PathVariable Long id,@PathVariable Long other,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u){service.removeDependency(id,other,w,u);return ApiResponse.ok("Dependency removed",null);}
 @GetMapping("/{id}/history") public ApiResponse<List<TaskStatusHistory>> history(@PathVariable Long id,@RequestHeader("X-Workspace-Id")Long w,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){Page<TaskStatusHistory> p=service.getHistory(id,w,page,size);return ApiResponse.okPage("History retrieved",p.getContent(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @PostMapping("/templates") public ApiResponse<TaskTemplate> template(@Valid @RequestBody TaskTemplateRequest r,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u,@RequestHeader(value="X-Workspace-Role",required=false)String role){return ApiResponse.ok("Template created",service.createTemplate(r,w,u,role));}
 @GetMapping("/templates") public ApiResponse<List<TaskTemplate>> templates(@RequestHeader("X-Workspace-Id")Long w){return ApiResponse.ok("Templates retrieved",service.templates(w));}
 @PostMapping("/templates/{id}/tasks") public ApiResponse<TaskDTO> fromTemplate(@PathVariable Long id,@RequestBody(required=false)TaskDTO d,@RequestHeader("X-Workspace-Id")Long w,@RequestHeader("X-User")String u,@RequestHeader(value="X-Workspace-Role",required=false)String role){return ApiResponse.ok("Task created from template",service.fromTemplate(id,d,w,u,role));}
}
