server.port=8090

spring.application.name=project-service

# Database Configuration
spring.datasource.url=jdbc:h2:mem:projectdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
task-service.url=${TASK_SERVICE_URL:http://localhost:8082}
