package com.example.task.service;
import com.fasterxml.jackson.databind.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.stereotype.Service;import org.springframework.web.client.RestTemplate;import java.util.*;
@Service public class TaskAccessValidator {
 private final RestTemplate http=new RestTemplate();private final ObjectMapper json=new ObjectMapper();private final String workspaceUrl,projectUrl;
 public TaskAccessValidator(@Value("${workspace-service.url:http://localhost:8092}")String w,@Value("${project-service.url:http://localhost:8090}")String p){workspaceUrl=w;projectUrl=p;}
 public void validate(Long workspaceId,Long projectId,String actor,String workspaceRole,String assignee,Set<String> watchers){if(workspaceId==null)throw new IllegalArgumentException("workspaceId is required");Set<String> users=new LinkedHashSet<>();if(assignee!=null&&!assignee.trim().isEmpty())users.add(assignee.trim());if(watchers!=null)users.addAll(watchers);Set<String> workspaceMembers=workspaceMembers(workspaceId);for(String u:users)if(!workspaceMembers.contains(u.toLowerCase()))throw new IllegalArgumentException(u+" is not a workspace member");if(projectId!=null){JsonNode data=project(workspaceId,projectId,actor,workspaceRole);if(data.path("project").path("workspaceId").asLong()!=workspaceId)throw new IllegalArgumentException("Project does not belong to workspace");Set<String> projectMembers=new HashSet<>();for(JsonNode m:data.path("members"))projectMembers.add(m.path("username").asText().toLowerCase());for(String u:users)if(!projectMembers.contains(u.toLowerCase()))throw new IllegalArgumentException(u+" is not a project member");}}
 private Set<String> workspaceMembers(Long id){try{JsonNode data=json.readTree(http.getForObject(workspaceUrl+"/api/workspaces/"+id,String.class)).path("data");Set<String>s=new HashSet<>();for(JsonNode m:data.path("members"))s.add(m.path("username").asText().toLowerCase());return s;}catch(Exception e){throw new IllegalStateException("Cannot verify workspace members",e);}}
 private JsonNode project(Long w,Long p,String actor,String role){try{HttpHeaders h=new HttpHeaders();h.set("X-Workspace-Id",w.toString());h.set("X-User",actor);if(role!=null)h.set("X-Workspace-Role",role);String body=http.exchange(projectUrl+"/api/projects/"+p,HttpMethod.GET,new HttpEntity<>(h),String.class).getBody();return json.readTree(body).path("data");}catch(Exception e){throw new IllegalArgumentException("Project is unavailable or access is denied",e);}}
}
