package com.example.task.service;
import com.example.common.exception.ResourceNotFoundException;import com.example.task.dto.*;import com.example.task.model.*;import com.example.task.repository.*;import org.springframework.data.domain.*;import org.springframework.orm.ObjectOptimisticLockingFailureException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;import java.util.*;import java.util.stream.Collectors;
@Service public class TaskService {
 private final TaskRepository tasks;private final CategoryRepository categories;private final TaskDependencyRepository dependencies;private final TaskStatusHistoryRepository history;private final TaskTemplateRepository templates;private final TaskAccessValidator access;private final TaskEventPublisher events;
 public TaskService(TaskRepository t,CategoryRepository c,TaskDependencyRepository d,TaskStatusHistoryRepository h,TaskTemplateRepository tr,TaskAccessValidator a,TaskEventPublisher e){tasks=t;categories=c;dependencies=d;history=h;templates=tr;access=a;events=e;}
 public Page<TaskDTO> getTasks(Long workspaceId,Long projectId,String assignee,Long parentTaskId,Status status,Priority priority,Long categoryId,String search,boolean includeArchived,int page,int size,String sort){if(page<0||size<1||size>100)throw new IllegalArgumentException("page must be >= 0 and size must be 1-100");Sort order="dueDate".equals(sort)?Sort.by("dueDate").ascending():Sort.by("position").ascending().and(Sort.by("createdAt").descending());return tasks.findFilteredTasks(workspaceId,projectId,blank(assignee),parentTaskId,status,priority,categoryId,blank(search),includeArchived,PageRequest.of(page,size,order)).map(this::dto);}
 public TaskDTO get(Long id,Long workspaceId){return dto(scoped(id,workspaceId));}
 public Page<TaskDTO> getSubtasks(Long id,Long workspaceId,int page,int size){scoped(id,workspaceId);if(page<0||size<1||size>100)throw new IllegalArgumentException("page must be >= 0 and size must be 1-100");return tasks.findByParentTaskIdAndWorkspaceIdAndArchivedFalse(id,workspaceId,PageRequest.of(page,size,Sort.by("position").ascending().and(Sort.by("createdAt").descending()))).map(this::dto);}
 @Transactional public TaskDTO duplicate(Long id,TaskDuplicateRequest request,Long workspaceId,String actor,String role){Task source=scoped(id,workspaceId);TaskDuplicateRequest r=request==null?new TaskDuplicateRequest():request;Long project=r.getProjectId()==null?source.getProjectId():r.getProjectId();if(r.isCopyDependencies()&&!Objects.equals(project,source.getProjectId()))throw new IllegalArgumentException("Dependencies can only be copied within the same project");TaskDTO copy=new TaskDTO();copy.setWorkspaceId(workspaceId);copy.setProjectId(project);copy.setParentTaskId(r.getParentTaskId());copy.setTitle(blank(r.getTitle())==null?source.getTitle()+" (copy)":r.getTitle().trim());copy.setDescription(source.getDescription());copy.setAssignee(source.getAssignee());copy.setWatchers(r.isCopyWatchers()?new LinkedHashSet<>(source.getWatchers()):new LinkedHashSet<>());copy.setPriority(source.getPriority());copy.setCategoryId(source.getCategory()==null?null:source.getCategory().getId());copy.setDueDate(r.getDueDate());copy.setRecurrenceRule(source.getRecurrenceRule());if(r.isCopyDependencies())copy.setDependencyIds(dependencies.findByTaskId(id).stream().map(TaskDependency::getDependsOnTaskId).collect(Collectors.toCollection(LinkedHashSet::new)));return create(copy,actor,role);}
 @Transactional public TaskDTO move(Long id,TaskMoveRequest request,Long workspaceId,String actor,String role){if(request==null)throw new IllegalArgumentException("Move request is required");Task task=scoped(id,workspaceId);version(task,request.getVersion());Long project=request.getProjectId()==null?task.getProjectId():request.getProjectId();boolean projectChanged=!Objects.equals(project,task.getProjectId());if(projectChanged&&(!dependencies.findByTaskId(id).isEmpty()||!tasks.findByParentTaskId(id).isEmpty()))throw new IllegalStateException("Remove dependencies and subtasks before moving task to another project");validateScope(workspaceId,project,actor,role,task.getAssignee(),task.getWatchers());validateParent(request.getParentTaskId(),workspaceId,project,id);if(request.getPosition()!=null&&request.getPosition()<0)throw new IllegalArgumentException("position must be >= 0");task.setProjectId(project);task.setParentTaskId(request.getParentTaskId());if(request.getPosition()!=null)task.setPosition(request.getPosition());Task saved=tasks.saveAndFlush(task);events.publish("moved",saved,actor);return dto(saved);}
 @Transactional public TaskDTO create(TaskDTO d,String actor,String workspaceRole){validateScope(d.getWorkspaceId(),d.getProjectId(),actor,workspaceRole,d.getAssignee(),d.getWatchers());validateParent(d.getParentTaskId(),d.getWorkspaceId(),d.getProjectId(),null);Task t=new Task();copy(d,t);t.setCreatedBy(actor);Task saved=tasks.save(t);addDependencies(saved,d.getDependencyIds());events.publish("created",saved,actor);return dto(saved);}
 @Transactional public TaskDTO update(Long id,TaskDTO d,Long workspaceId,String actor,String role){Task t=scoped(id,workspaceId);version(t,d.getVersion());Long targetWorkspace=d.getWorkspaceId()==null?t.getWorkspaceId():d.getWorkspaceId();if(!targetWorkspace.equals(workspaceId))throw new SecurityException("Cannot move task to another workspace");validateScope(targetWorkspace,d.getProjectId(),actor,role,d.getAssignee(),d.getWatchers());validateParent(d.getParentTaskId(),targetWorkspace,d.getProjectId(),id);Status old=t.getStatus();copy(d,t);Task saved=tasks.saveAndFlush(t);syncDependencies(saved,d.getDependencyIds());statusHistory(saved,old,actor);spawnRecurrence(saved,actor,role);events.publish("updated",saved,actor);return dto(saved);}
 @Transactional public TaskDTO status(Long id,Status status,Long expectedVersion,Long workspaceId,String actor,String role){Task t=scoped(id,workspaceId);version(t,expectedVersion);Status old=t.getStatus();t.setStatus(status);Task saved=tasks.saveAndFlush(t);statusHistory(saved,old,actor);spawnRecurrence(saved,actor,role);events.publish("status-changed",saved,actor);return dto(saved);}
 @Transactional public List<TaskDTO> bulk(BulkTaskUpdateRequest request,Long workspaceId,String actor,String role){if(request==null||request.getItems()==null||request.getItems().isEmpty())throw new IllegalArgumentException("Bulk items are required");if(request.getItems().size()>100)throw new IllegalArgumentException("Bulk update supports at most 100 tasks");Set<Long> ids=new HashSet<>();for(BulkTaskUpdateRequest.Item i:request.getItems())if(i.getId()==null||!ids.add(i.getId()))throw new IllegalArgumentException("Bulk task IDs must be present and unique");List<Task> changed=new ArrayList<>();for(BulkTaskUpdateRequest.Item i:request.getItems()){Task t=scoped(i.getId(),workspaceId);version(t,i.getVersion());String assignee=i.getAssignee()==null?t.getAssignee():blank(i.getAssignee());validateScope(t.getWorkspaceId(),t.getProjectId(),actor,role,assignee,t.getWatchers());Status old=t.getStatus();if(i.getStatus()!=null)t.setStatus(i.getStatus());if(i.getPriority()!=null)t.setPriority(i.getPriority());if(i.getAssignee()!=null)t.setAssignee(assignee);if(i.getDueDate()!=null)t.setDueDate(i.getDueDate());statusHistory(t,old,actor);changed.add(t);}tasks.saveAll(changed);tasks.flush();for(Task t:changed){spawnRecurrence(t,actor,role);events.publish("updated",t,actor);}return changed.stream().map(this::dto).collect(Collectors.toList());}
 @Transactional public TaskDTO archive(Long id,Long expectedVersion,Long workspaceId,String actor){Task t=scoped(id,workspaceId);version(t,expectedVersion);t.setArchived(true);t.setArchivedAt(LocalDateTime.now());t.setArchivedBy(actor);Task saved=tasks.saveAndFlush(t);events.publish("archived",saved,actor);return dto(saved);}
 @Transactional public TaskDTO restore(Long id,Long expectedVersion,Long workspaceId,String actor){Task t=scopedAllowArchived(id,workspaceId);version(t,expectedVersion);if(!t.isArchived())throw new IllegalStateException("Task is not archived");t.setArchived(false);t.setArchivedAt(null);t.setArchivedBy(null);Task saved=tasks.saveAndFlush(t);events.publish("restored",saved,actor);return dto(saved);}
 @Transactional public TaskDTO watcher(Long id,String username,boolean add,Long workspaceId,String actor,String role){Task t=scoped(id,workspaceId);String user=required(username,"username");Set<String> target=new LinkedHashSet<>(t.getWatchers());if(add)target.add(user);else target.remove(user);validateScope(t.getWorkspaceId(),t.getProjectId(),actor,role,t.getAssignee(),target);t.setWatchers(target);Task saved=tasks.save(t);events.publish("updated",saved,actor);return dto(saved);}
 @Transactional public TaskDTO addDependency(Long id,Long other,Long workspaceId,String actor){Task t=scoped(id,workspaceId),d=scoped(other,workspaceId);if(id.equals(other))throw new IllegalArgumentException("Task cannot depend on itself");if(!Objects.equals(t.getProjectId(),d.getProjectId()))throw new IllegalArgumentException("Dependencies must belong to the same project");if(path(other,id,new HashSet<>()))throw new IllegalArgumentException("Dependency would create a cycle");if(!dependencies.existsByTaskIdAndDependsOnTaskId(id,other))dependencies.save(new TaskDependency(id,other));events.publish("updated",t,actor);return dto(t);}
 @Transactional public void removeDependency(Long id,Long other,Long workspaceId,String actor){Task t=scoped(id,workspaceId);dependencies.deleteByTaskIdAndDependsOnTaskId(id,other);events.publish("updated",t,actor);}
 public List<TaskStatusHistory> getHistory(Long id,Long workspaceId){scoped(id,workspaceId);return history.findByTaskIdOrderByChangedAtDesc(id);}
 public Page<TaskStatusHistory> getHistory(Long id,Long workspaceId,int page,int size){scoped(id,workspaceId);if(page<0||size<1||size>100)throw new IllegalArgumentException("page must be >= 0 and size must be 1-100");return history.findByTaskId(id,PageRequest.of(page,size,Sort.by("changedAt").descending()));}
 public TaskStatsDTO stats(Long w){if(w==null)throw new IllegalArgumentException("workspaceId is required");return new TaskStatsDTO(tasks.countByWorkspaceIdAndArchivedFalse(w),count(w,Status.TODO),count(w,Status.IN_PROGRESS),count(w,Status.COMPLETED));}
 @Transactional public TaskTemplate createTemplate(TaskTemplateRequest r,Long w,String actor,String role){if(templates.existsByWorkspaceIdAndNameIgnoreCase(w,r.getName()))throw new IllegalArgumentException("Template name already exists");validateScope(w,r.getProjectId(),actor,role,r.getDefaultAssignee(),Collections.emptySet());TaskTemplate t=new TaskTemplate();t.setWorkspaceId(w);t.setProjectId(r.getProjectId());t.setName(required(r.getName(),"name"));t.setTitle(required(r.getTitle(),"title"));t.setDescription(r.getDescription());t.setPriority(r.getPriority()==null?Priority.MEDIUM:r.getPriority());t.setRecurrenceRule(r.getRecurrenceRule());t.setDefaultAssignee(blank(r.getDefaultAssignee()));t.setCreatedBy(actor);return templates.save(t);}
 public List<TaskTemplate> templates(Long w){return templates.findByWorkspaceIdOrderByName(w);}
 @Transactional public TaskDTO fromTemplate(Long templateId,TaskDTO overrides,Long w,String actor,String role){TaskTemplate x=templates.findById(templateId).orElseThrow(()->new IllegalArgumentException("Template not found"));if(!w.equals(x.getWorkspaceId()))throw new SecurityException("Template belongs to another workspace");TaskDTO d=overrides==null?new TaskDTO():overrides;d.setWorkspaceId(w);if(d.getProjectId()==null)d.setProjectId(x.getProjectId());if(d.getTitle()==null)d.setTitle(x.getTitle());if(d.getDescription()==null)d.setDescription(x.getDescription());if(d.getPriority()==null)d.setPriority(x.getPriority());if(d.getAssignee()==null)d.setAssignee(x.getDefaultAssignee());if(d.getRecurrenceRule()==null)d.setRecurrenceRule(x.getRecurrenceRule());return create(d,actor,role);}
 private void spawnRecurrence(Task source,String actor,String role){if(source.getStatus()!=Status.COMPLETED||source.getRecurrenceRule()==null||source.isRecurrenceGenerated())return;source.setRecurrenceGenerated(true);tasks.save(source);Task next=new Task();next.setWorkspaceId(source.getWorkspaceId());next.setProjectId(source.getProjectId());next.setTitle(source.getTitle());next.setDescription(source.getDescription());next.setPriority(source.getPriority());next.setAssignee(source.getAssignee());next.setWatchers(new LinkedHashSet<>(source.getWatchers()));next.setRecurrenceRule(source.getRecurrenceRule());next.setCreatedBy(actor);if(source.getDueDate()!=null){switch(source.getRecurrenceRule()){case DAILY:next.setDueDate(source.getDueDate().plusDays(1));break;case WEEKLY:next.setDueDate(source.getDueDate().plusWeeks(1));break;case MONTHLY:next.setDueDate(source.getDueDate().plusMonths(1));}}Task saved=tasks.save(next);events.publish("created",saved,actor);}
 private void validateScope(Long w,Long p,String actor,String role,String assignee,Set<String> watchers){access.validate(w,p,actor,role,blank(assignee),watchers==null?Collections.emptySet():watchers);}
 private void copy(TaskDTO d,Task t){t.setTitle(required(d.getTitle(),"title"));t.setDescription(d.getDescription());t.setWorkspaceId(d.getWorkspaceId()==null?t.getWorkspaceId():d.getWorkspaceId());t.setProjectId(d.getProjectId());t.setParentTaskId(d.getParentTaskId());t.setAssignee(blank(d.getAssignee()));t.setWatchers(d.getWatchers());t.setStatus(d.getStatus()==null?Status.TODO:d.getStatus());t.setPriority(d.getPriority()==null?Priority.MEDIUM:d.getPriority());t.setDueDate(d.getDueDate());t.setRecurrenceRule(d.getRecurrenceRule());if(d.getPosition()!=null)t.setPosition(d.getPosition());t.setCategory(d.getCategoryId()==null?null:categories.findById(d.getCategoryId()).orElseThrow(()->new ResourceNotFoundException("Category","id",d.getCategoryId())));}
 private Task scoped(Long id,Long w){Task t=scopedAllowArchived(id,w);if(t.isArchived())throw new IllegalStateException("Archived task is read-only");return t;}private Task scopedAllowArchived(Long id,Long w){Task t=tasks.findById(id).orElseThrow(()->new ResourceNotFoundException("Task","id",id));if(w!=null&&!w.equals(t.getWorkspaceId()))throw new SecurityException("Task belongs to another workspace");return t;}private TaskDTO dto(Task t){TaskDTO d=new TaskDTO(t);d.setDependencyIds(dependencies.findByTaskId(t.getId()).stream().map(TaskDependency::getDependsOnTaskId).collect(Collectors.toCollection(LinkedHashSet::new)));return d;}
 private void validateParent(Long pid,Long w,Long p,Long self){if(pid==null)return;if(pid.equals(self))throw new IllegalArgumentException("Task cannot be its own parent");Task parent=scoped(pid,w);if(!Objects.equals(p,parent.getProjectId()))throw new IllegalArgumentException("Subtask must use parent project");Set<Long>seen=new HashSet<>();while(parent.getParentTaskId()!=null){if(!seen.add(parent.getId())||Objects.equals(parent.getParentTaskId(),self))throw new IllegalArgumentException("Parent relationship would create a cycle");parent=scoped(parent.getParentTaskId(),w);}}private void addDependencies(Task t,Set<Long> ids){if(ids!=null)for(Long id:ids)addDependency(t.getId(),id,t.getWorkspaceId(),t.getCreatedBy());}private void syncDependencies(Task t,Set<Long> ids){if(ids==null)return;Set<Long>target=new LinkedHashSet<>(ids);for(Long other:target){Task dependency=scoped(other,t.getWorkspaceId());if(t.getId().equals(other))throw new IllegalArgumentException("Task cannot depend on itself");if(!Objects.equals(t.getProjectId(),dependency.getProjectId()))throw new IllegalArgumentException("Dependencies must belong to the same project");if(path(other,t.getId(),new HashSet<>()))throw new IllegalArgumentException("Dependency would create a cycle");}dependencies.deleteByTaskId(t.getId());for(Long other:target)dependencies.save(new TaskDependency(t.getId(),other));}private boolean path(Long from,Long target,Set<Long>s){if(from.equals(target))return true;if(!s.add(from))return false;for(TaskDependency d:dependencies.findByTaskId(from))if(path(d.getDependsOnTaskId(),target,s))return true;return false;}
 private void statusHistory(Task t,Status old,String actor){if(old!=t.getStatus())history.save(new TaskStatusHistory(t.getId(),old,t.getStatus(),actor));}private void version(Task t,Long v){if(v==null||!v.equals(t.getVersion()))throw new ObjectOptimisticLockingFailureException(Task.class,t.getId());}private long count(Long w,Status s){return tasks.countByWorkspaceIdAndStatusAndArchivedFalse(w,s);}private String blank(String s){return s==null||s.trim().isEmpty()?null:s.trim();}private String required(String s,String f){String v=blank(s);if(v==null)throw new IllegalArgumentException(f+" is required");return v;}
}
