package com.example.task.service;
import com.example.task.dto.*;import com.example.task.model.*;import com.example.task.repository.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.mock.mockito.MockBean;import org.springframework.data.domain.Page;import org.springframework.orm.ObjectOptimisticLockingFailureException;
import java.time.LocalDateTime;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(properties="task.events.enabled=false") class TaskServiceIntegrationTest {
 @Autowired TaskService service;@Autowired TaskRepository tasks;@Autowired TaskDependencyRepository deps;@Autowired TaskStatusHistoryRepository history;@Autowired TaskTemplateRepository templates;@MockBean TaskAccessValidator access;
 @BeforeEach void clean(){deps.deleteAll();history.deleteAll();tasks.deleteAll();templates.deleteAll();}
 @Test void createsTaskWithScopeAssigneeAndWatchers(){TaskDTO d=request("One",1L,10L);d.setAssignee("bob");d.setWatchers(Set.of("alice","carol"));TaskDTO saved=service.create(d,"alice","MEMBER");assertEquals(1L,saved.getWorkspaceId());assertEquals(2,saved.getWatchers().size());assertNotNull(saved.getVersion());}
 @Test void paginatesAndFiltersActiveTasks(){for(int i=0;i<5;i++)service.create(request("Task "+i,1L,10L),"alice","MEMBER");TaskDTO archived=service.create(request("Old",1L,10L),"alice","MEMBER");service.archive(archived.getId(),archived.getVersion(),1L,"alice");Page<TaskDTO> page=service.getTasks(1L,null,null,null,null,null,null,null,false,0,10,"position");assertEquals(5,page.getTotalElements());}
 @Test void validatesSubtaskScope(){TaskDTO parent=service.create(request("Parent",1L,10L),"alice","MEMBER");TaskDTO child=request("Child",2L,10L);child.setParentTaskId(parent.getId());assertThrows(SecurityException.class,()->service.create(child,"alice","MEMBER"));}
 @Test void preventsDependencyCycles(){TaskDTO a=service.create(request("A",1L,10L),"alice","MEMBER"),b=service.create(request("B",1L,10L),"alice","MEMBER");service.addDependency(a.getId(),b.getId(),1L,"alice");assertThrows(IllegalArgumentException.class,()->service.addDependency(b.getId(),a.getId(),1L,"alice"));}
 @Test void rejectsStaleVersion(){TaskDTO saved=service.create(request("A",1L,10L),"alice","MEMBER");TaskDTO stale=request("Changed",1L,10L);stale.setVersion(saved.getVersion()+1);assertThrows(ObjectOptimisticLockingFailureException.class,()->service.update(saved.getId(),stale,1L,"alice","MEMBER"));}
 @Test void completingRecurringTaskCreatesNextOccurrence(){TaskDTO d=request("Daily",1L,10L);d.setRecurrenceRule(RecurrenceRule.DAILY);d.setDueDate(LocalDateTime.now());TaskDTO saved=service.create(d,"alice","MEMBER");service.status(saved.getId(),Status.COMPLETED,saved.getVersion(),1L,"alice","MEMBER");assertEquals(2,tasks.count());assertEquals(1,tasks.findAll().stream().filter(t->t.getStatus()==Status.TODO).count());}
 @Test void bulkUpdateIsVersionChecked(){TaskDTO a=service.create(request("A",1L,10L),"alice","MEMBER");BulkTaskUpdateRequest.Item item=new BulkTaskUpdateRequest.Item();item.setId(a.getId());item.setVersion(a.getVersion());item.setPriority(Priority.URGENT);BulkTaskUpdateRequest r=new BulkTaskUpdateRequest();r.setItems(List.of(item));assertEquals(Priority.URGENT,service.bulk(r,1L,"alice","MEMBER").get(0).getPriority());}
 @Test void updateSynchronizesDependencies(){TaskDTO a=service.create(request("A",1L,10L),"alice","MEMBER"),b=service.create(request("B",1L,10L),"alice","MEMBER"),c=service.create(request("C",1L,10L),"alice","MEMBER");TaskDTO update=request("A changed",1L,10L);update.setVersion(a.getVersion());update.setDependencyIds(Set.of(b.getId(),c.getId()));TaskDTO saved=service.update(a.getId(),update,1L,"alice","MEMBER");assertEquals(Set.of(b.getId(),c.getId()),saved.getDependencyIds());}
 @Test void rejectsMultiLevelParentCycle(){TaskDTO parent=service.create(request("Parent",1L,10L),"alice","MEMBER");TaskDTO childRequest=request("Child",1L,10L);childRequest.setParentTaskId(parent.getId());TaskDTO child=service.create(childRequest,"alice","MEMBER");TaskDTO update=request("Parent",1L,10L);update.setVersion(parent.getVersion());update.setParentTaskId(child.getId());assertThrows(IllegalArgumentException.class,()->service.update(parent.getId(),update,1L,"alice","MEMBER"));}
 @Test void rejectsDuplicateIdsInBulkUpdate(){TaskDTO a=service.create(request("A",1L,10L),"alice","MEMBER");BulkTaskUpdateRequest.Item first=new BulkTaskUpdateRequest.Item();first.setId(a.getId());first.setVersion(a.getVersion());BulkTaskUpdateRequest r=new BulkTaskUpdateRequest();r.setItems(List.of(first,first));assertThrows(IllegalArgumentException.class,()->service.bulk(r,1L,"alice","MEMBER"));}
 @Test void paginatesStatusHistory(){TaskDTO task=service.create(request("A",1L,10L),"alice","MEMBER");TaskDTO doing=service.status(task.getId(),Status.IN_PROGRESS,task.getVersion(),1L,"alice","MEMBER");service.status(task.getId(),Status.COMPLETED,doing.getVersion(),1L,"alice","MEMBER");assertEquals(2,service.getHistory(task.getId(),1L,0,1).getTotalElements());assertEquals(1,service.getHistory(task.getId(),1L,0,1).getContent().size());}
 private TaskDTO request(String title,Long w,Long p){TaskDTO d=new TaskDTO();d.setTitle(title);d.setWorkspaceId(w);d.setProjectId(p);return d;}
}
